#!/usr/bin/env sh

set -eu

ROOT_DIR=$(git rev-parse --show-toplevel)

cd "$ROOT_DIR"

echo "Running Deptrac..."
composer deptrac

echo "Running ESLint..."
npm run lint

echo "Generating OpenAPI specification..."
composer docs:generate

git add docs/openapi.yaml docs/openapi.json
